version: "3"

volumes:
  produtosdata:
      
networks:
  backend:

services:

  mysql:
    image: "mysql:5.7"
    volumes:
        - produtosdata:/var/lib/mysql
        - ./_MySQL_Init_Script:/docker-entrypoint-initdb.d
    networks:
        - backend
    environment:
        - MYSQL_ROOT_PASSWORD=root
        - bind-address=0.0.0.0

  mvc:
    build :
      context : .
      dockerfile : Dockerfile.dev

    networks :
      - backend

    ports:
      - 5000:80
    environment :
      - DBHOST=mysql
      - bind-address=0.0.0.0
      - ASPNETCORE_ENVIRONMENT=Development
      - applicationUrl=https://localhost:5001;http://localhost:5000  

    depends_on :
      - mysql
      